import type { Domain } from './types';
import { subDays, addDays, formatISO } from 'date-fns';

const today = new Date();

export const domains: Domain[] = [
  {
    id: 1,
    domainName: 'innovatech.com',
    status: 'active',
    collectionDate: formatISO(subDays(today, 10)),
    renewalDate: formatISO(addDays(today, 30)),
    clientName: 'Alice Johnson',
    clientEmail: 'alice.j@example.com',
    registrar: 'GoDaddy',
    outstandingBalance: 0,
  },
  {
    id: 2,
    domainName: 'quantumleap.ai',
    status: 'active',
    collectionDate: formatISO(subDays(today, 5)),
    renewalDate: formatISO(addDays(today, 15)),
    clientName: 'Bob Williams',
    clientEmail: 'bob.w@example.com',
    registrar: 'Namecheap',
    outstandingBalance: 50.00,
  },
  {
    id: 3,
    domainName: 'ecowear.co',
    status: 'inactive',
    collectionDate: formatISO(subDays(today, 90)),
    renewalDate: formatISO(subDays(today, 5)),
    clientName: 'Charlie Brown',
    clientEmail: 'charlie.b@example.com',
    registrar: 'Google Domains',
    outstandingBalance: 25.00,
  },
  {
    id: 4,
    domainName: 'healthfirst.app',
    status: 'active',
    collectionDate: formatISO(addDays(today, 20)),
    renewalDate: formatISO(addDays(today, 120)),
    clientName: 'Diana Prince',
    clientEmail: 'diana.p@example.com',
    registrar: 'Cloudflare',
    outstandingBalance: 0,
  },
  {
    id: 5,
    domainName: 'artisanbakers.net',
    status: 'active',
    collectionDate: formatISO(subDays(today, 1)),
    renewalDate: formatISO(addDays(today, 3)),
    clientName: 'Ethan Hunt',
    clientEmail: 'ethan.h@example.com',
    registrar: 'Porkbun',
    outstandingBalance: 0,
  },
    {
    id: 6,
    domainName: 'nextgen-solutions.io',
    status: 'active',
    collectionDate: formatISO(subDays(today, 45)),
    renewalDate: formatISO(addDays(today, 250)),
    clientName: 'Fiona Glenanne',
    clientEmail: 'fiona.g@example.com',
    registrar: 'Namecheap',
    outstandingBalance: 0,
  },
  {
    id: 7,
    domainName: 'vintagefinds.store',
    status: 'inactive',
    collectionDate: formatISO(subDays(today, 120)),
    renewalDate: formatISO(subDays(today, 30)),
    clientName: 'George Costanza',
    clientEmail: 'george.c@example.com',
    registrar: 'GoDaddy',
    outstandingBalance: 75.50,
  },
];
